<?php $presets["business"] = array (
  'of-preset' => 'business',
  'branding-header_logo' => 
  array (
    0 => '/images/backgrounds/branding/business_logo-top.png?w=192&h=60',
    1 => 0,
  ),
  'branding-retina_header_logo' => 
  array (
    0 => '/images/backgrounds/branding/business_logo-top-retina.png?w=384&h=120',
    1 => 0,
  ),
  'branding-header_mobile_logo' => 
  array (
    0 => '/images/backgrounds/branding/business_logo-mob.png?w=144&h=150',
    1 => 0,
  ),
  'branding-retina_header_mobile_logo' => 
  array (
    0 => '/images/backgrounds/branding/business_logo-mob-retina.png?w=288&h=300',
    1 => 0,
  ),
  'branding-footer_logo' => 
  array (
    0 => '/images/backgrounds/branding/business_logo-bottom.png?w=147&h=50',
    1 => 0,
  ),
  'branding-retina_footer_logo' => 
  array (
    0 => '/images/backgrounds/branding/business_logo-bottom-retina.png?w=294&h=100',
    1 => 0,
  ),
  'branding-copyrights' => '',
  'branding-dt_credits' => '1',
  'menu-parent_menu_clickable' => '1',
  'menu-first_font' => 'Tahoma',
  'menu-first_font_bold' => '1',
  'menu-first_font_italic' => '0',
  'menu-first_font_size' => '12',
  'menu-first_font_upper' => '1',
  'menu-first_font_color' => '#ffffff',
  'menu-first_font_color_active' => '#2be28c',
  'menu-first_hoover_line_color' => '#2be28c',
  'menu-first_hoover_color' => '#001842',
  'menu-first_hoover_opacity' => 30,
  'menu-second_font_color' => '#1e1e1d',
  'menu-second_font_color_active' => '#1ebd73',
  'menu-second_bg_color' => '#ffffff',
  'menu-second_bg_opacity' => 100,
  'buttons-bg_color' => '#12c8a2',
  'buttons-font_color' => '#ffffff',
  'buttons-font_shadow' => '#0c997a',
  'buttons-active_bg_color' => '#1c8dc9',
  'buttons-active_font_color' => '#ffffff',
  'buttons-active_font_shadow' => '#13618a',
  'main-icons_style' => 'black',
  'main-icons_opacity' => 66,
  'main_bg-bg_color' => '#f2f2f4',
  'background-bg_image' => 'none',
  'main_bg-bg_repeat' => 'repeat',
  'main_bg-bg_vertical_pos' => 'top',
  'main_bg-bg_horizontal_pos' => 'center',
  'main_bg-bg_fixed' => '0',
  'main_bg-bg_mobile_hide' => '0',
  'main_bg-overlay_enable' => '0',
  'main_bg-overlay_image' => 'none',
  'divs_and_heads-content_wide_divider' => '/images/backgrounds/content/div-big/full/business_div-big.gif',
  'divs_and_heads-content_wide_divider_repeatx' => '1',
  'divs_and_heads-content_narrow_divider' => '/images/backgrounds/content/div-small/full/business_div-small.gif',
  'divs_and_heads-content_narrow_divider_repeatx' => '1',
  'widgetcodes-bg_color' => '#ffffff',
  'widgetcodes-bg_opacity' => 100,
  'header-icons_style' => 'black',
  'header-icons_opacity' => 94,
  'header-icons_bg_color' => '#ffffff',
  'header-icons_bg_opacity' => 21,
  'header_logo_menu-bg_color' => '#064672',
  'header_logo_menu-bg_image' => '/images/backgrounds/header/under-menu/full/business_under-menu.jpg',
  'header_logo_menu-bg_repeat' => 'repeat-x',
  'header_logo_menu-bg_vertical_pos' => 'top',
  'header_logo_menu-bg_horizontal_pos' => 'center',
  'header_homepage-bg_image' => '/images/backgrounds/header/art-header-main/full/business_art-header-main.jpg',
  'header_homepage-bg_repeat' => 'repeat-x',
  'header_homepage-bg_vertical_pos' => 'top',
  'header_homepage-bg_horizontal_pos' => 'center',
  'header_content-bg_image' => '/images/backgrounds/header/art-header-inner/full/business_art_header-inner.png',
  'header_content-bg_repeat' => 'repeat-x',
  'header_content-bg_vertical_pos' => 'top',
  'header_content-bg_horizontal_pos' => 'center',
  'top_line-bg_color' => '#000c1b',
  'top_line-bg_image' => 'none',
  'top_line-bg_repeat' => 'repeat',
  'top_line-bg_vertical_pos' => 'top',
  'top_line-bg_horizontal_pos' => 'center',
  'footer-bg_color' => '#071226',
  'footer-bg_opacity' => 100,
  'footer-bg_image' => '/images/backgrounds/footer/pattern-footer/full/business_pattern-footer.jpg',
  'footer-bg_repeat' => 'repeat',
  'footer-bg_vertical_pos' => 'top',
  'footer-bg_horizontal_pos' => 'center',
  'divs_and_heads-footer_wide_divider' => '/images/backgrounds/footer/line-decor/full/business_line-decor.png',
  'divs_and_heads-footer_wide_divider_hide_if_no_footer' => '0',
  'divs_and_heads-footer_wide_divider_repeatx' => '1',
  'widgetcodes_footer-bg_color' => '#071226',
  'widgetcodes_footer-bg_opacity' => 40,
  'bottom_line-bg_color' => '#000c1b',
  'bottom_line-bg_opacity' => 100,
  'bottom_line-bg_image' => 'none',
  'bottom_line-bg_repeat' => 'repeat',
  'bottom_line-bg_vertical_pos' => 'top',
  'bottom_line-bg_horizontal_pos' => 'center',
  'boxed_layout-enable' => '0',
  'boxed_layout-bg_color' => '#ffffff',
  'boxed_layout-bg_opacity' => 34,
  'boxed_layout-bg_image' => 'none',
  'boxed_layout-shadow_color' => '#000000',
  'boxed_layout-shadow_opacity' => 20,
  'accent-icons_style' => 'white',
  'accent-color' => '#20a0e6',
  'fonts-font_family' => 'Arial_Bold',
  'fonts-font_size' => 12,
  'fonts_content-topline_color' => '#ffffff',
  'fonts_content-primary_color' => '#545a60',
  'fonts_content-secondary_color' => '#12ba84',
  'fonts-links_text_color' => '#0f6c9e',
  'fonts_footer-primary_color' => '#e5e5e5',
  'fonts_footer-secondary_color' => '#12ba84',
  'fonts_content-bottomline_color' => '#fafafa',
  'fonts-list' => 'Bitter',
  'fonts-headers_size_h1' => '27',
  'fonts-headers_size_h2' => '19',
  'fonts-headers_size_h3' => '16',
  'fonts-headers_size_h4' => '14',
  'fonts-headers_size_h5' => '12',
  'fonts-headers_size_h6' => '10',
  'fonts_content-headers_color' => '#292a2b',
  'fonts_footer-headers_bottom_color' => '#fafafa',
  'branding-favicon' => '',
  'header_logo_menu-height' => '100',
); ?>