<?php $presets["dark"] = array (
  'of-preset' => 'dark',
  'branding-header_logo' => 
  array (
    0 => '/images/backgrounds/branding/dark_logo-top.png?w=191&h=60',
    1 => 0,
  ),
  'branding-retina_header_logo' => 
  array (
    0 => '/images/backgrounds/branding/dark_logo-top-retina.png?w=382&h=120',
    1 => 0,
  ),
  'branding-header_mobile_logo' => 
  array (
    0 => '/images/backgrounds/branding/dark_logo-mob.png?w=144&h=150',
    1 => 0,
  ),
  'branding-retina_header_mobile_logo' => 
  array (
    0 => '/images/backgrounds/branding/dark_logo-mob-retina.png?w=288&h=300',
    1 => 0,
  ),
  'branding-footer_logo' => 
  array (
    0 => '/images/backgrounds/branding/dark_logo-bottom.png?w=150&h=38',
    1 => 0,
  ),
  'branding-retina_footer_logo' => 
  array (
    0 => '/images/backgrounds/branding/dark_logo-bottom-retina.png?w=300&h=76',
    1 => 0,
  ),
  'branding-copyrights' => '',
  'branding-dt_credits' => '1',
  'menu-parent_menu_clickable' => '1',
  'menu-first_font' => 'Tahoma',
  'menu-first_font_bold' => '1',
  'menu-first_font_italic' => '0',
  'menu-first_font_size' => '12',
  'menu-first_font_upper' => '1',
  'menu-first_font_color' => '#ffffff',
  'menu-first_font_color_active' => '#87c108',
  'menu-first_hoover_line_color' => '#87c108',
  'menu-first_hoover_color' => '#252525',
  'menu-first_hoover_opacity' => 100,
  'menu-second_font_color' => '#252525',
  'menu-second_font_color_active' => '#04a9c2',
  'menu-second_bg_color' => '#fcfcfc',
  'menu-second_bg_opacity' => 100,
  'buttons-bg_color' => '#28bcd3',
  'buttons-font_color' => '#ffffff',
  'buttons-font_shadow' => '#0d7b8f',
  'buttons-active_bg_color' => '#97d60f',
  'buttons-active_font_color' => '#ffffff',
  'buttons-active_font_shadow' => '#638716',
  'main-icons_style' => 'white',
  'main-icons_opacity' => 18,
  'main_bg-bg_color' => '#1a1a1a',
  'background-bg_image' => 'none',
  'main_bg-bg_repeat' => 'repeat',
  'main_bg-bg_vertical_pos' => 'center',
  'main_bg-bg_horizontal_pos' => 'center',
  'main_bg-bg_fixed' => '0',
  'main_bg-bg_mobile_hide' => '1',
  'main_bg-overlay_enable' => '0',
  'main_bg-overlay_image' => 'none',
  'divs_and_heads-content_wide_divider' => '/images/backgrounds/content/div-big/full/dark_div-big.png',
  'divs_and_heads-content_wide_divider_repeatx' => '1',
  'divs_and_heads-content_narrow_divider' => '/images/backgrounds/content/div-small/full/dark_div-small.gif',
  'divs_and_heads-content_narrow_divider_repeatx' => '1',
  'widgetcodes-bg_color' => '#2c2c2c',
  'widgetcodes-bg_opacity' => 100,
  'header-icons_style' => 'black',
  'header-icons_opacity' => 61,
  'header-icons_bg_color' => '#454545',
  'header-icons_bg_opacity' => 100,
  'header_logo_menu-bg_color' => '#101010',
  'header_logo_menu-bg_image' => '/images/backgrounds/header/under-menu/full/dark_under-menu.gif',
  'header_logo_menu-bg_repeat' => 'repeat-x',
  'header_logo_menu-bg_vertical_pos' => 'bottom',
  'header_logo_menu-bg_horizontal_pos' => 'center',
  'header_homepage-bg_image' => '/images/backgrounds/header/art-header-main/full/dark_art-header-main.gif',
  'header_homepage-bg_repeat' => 'repeat-x',
  'header_homepage-bg_vertical_pos' => 'top',
  'header_homepage-bg_horizontal_pos' => 'center',
  'header_content-bg_image' => 'none',
  'header_content-bg_repeat' => 'repeat-x',
  'header_content-bg_vertical_pos' => 'top',
  'header_content-bg_horizontal_pos' => 'center',
  'top_line-bg_color' => '#252525',
  'top_line-bg_image' => 'none',
  'top_line-bg_repeat' => 'repeat-x',
  'top_line-bg_vertical_pos' => 'bottom',
  'top_line-bg_horizontal_pos' => 'center',
  'footer-bg_color' => '#101010',
  'footer-bg_opacity' => 100,
  'footer-bg_image' => 'none',
  'footer-bg_repeat' => 'repeat',
  'footer-bg_vertical_pos' => 'center',
  'footer-bg_horizontal_pos' => 'center',
  'divs_and_heads-footer_wide_divider' => '/images/backgrounds/footer/line-decor/full/dark_line-decor.gif',
  'divs_and_heads-footer_wide_divider_hide_if_no_footer' => '1',
  'divs_and_heads-footer_wide_divider_repeatx' => '1',
  'widgetcodes_footer-bg_color' => '#252525',
  'widgetcodes_footer-bg_opacity' => 100,
  'bottom_line-bg_color' => '#252525',
  'bottom_line-bg_opacity' => 100,
  'bottom_line-bg_image' => '/images/backgrounds/footer/line-bottom/full/dark_line-bottom.gif',
  'bottom_line-bg_repeat' => 'repeat-x',
  'bottom_line-bg_vertical_pos' => 'top',
  'bottom_line-bg_horizontal_pos' => 'center',
  'boxed_layout-enable' => '0',
  'boxed_layout-bg_color' => '#ffffff',
  'boxed_layout-bg_opacity' => 34,
  'boxed_layout-bg_image' => 'none',
  'boxed_layout-shadow_color' => '#000000',
  'boxed_layout-shadow_opacity' => 20,
  'accent-icons_style' => 'white',
  'accent-color' => '#97d60f',
  'fonts-font_family' => 'Arial_Bold',
  'fonts-font_size' => 12,
  'fonts_content-topline_color' => '#f7f7f7',
  'fonts_content-primary_color' => '#8a8a8a',
  'fonts_content-secondary_color' => '#fafafa',
  'fonts-links_text_color' => '#0aaecb',
  'fonts_footer-primary_color' => '#ebebeb',
  'fonts_footer-secondary_color' => '#0aaecb',
  'fonts_content-bottomline_color' => '#767676',
  'fonts-list' => 'Bitter',
  'fonts-headers_size_h1' => '27',
  'fonts-headers_size_h2' => '19',
  'fonts-headers_size_h3' => '16',
  'fonts-headers_size_h4' => '14',
  'fonts-headers_size_h5' => '12',
  'fonts-headers_size_h6' => '10',
  'fonts_content-headers_color' => '#f5f5f5',
  'fonts_footer-headers_bottom_color' => '#f5f5f5',
  'branding-favicon' => '',
  'header_logo_menu-height' => '100',
); ?>