<?php $presets["grunge"] = array (
  'of-preset' => 'grunge',
  'branding-header_logo' => 
  array (
    0 => '/images/backgrounds/branding/grunge_logo-top.png?w=193&h=60',
    1 => 0,
  ),
  'branding-retina_header_logo' => 
  array (
    0 => '/images/backgrounds/branding/grunge_logo-top-retina.png?w=386&h=120',
    1 => 0,
  ),
  'branding-header_mobile_logo' => 
  array (
    0 => '/images/backgrounds/branding/grunge_logo-mob.png?w=144&h=150',
    1 => 0,
  ),
  'branding-retina_header_mobile_logo' => 
  array (
    0 => '/images/backgrounds/branding/grunge_logo-mob-retina.png?w=288&h=300',
    1 => 0,
  ),
  'branding-footer_logo' => 
  array (
    0 => '/images/backgrounds/branding/grunge_logo-bottom.png?w=146&h=50',
    1 => 0,
  ),
  'branding-retina_footer_logo' => 
  array (
    0 => '/images/backgrounds/branding/grunge_logo-bottom-retina.png?w=292&h=100',
    1 => 0,
  ),
  'branding-copyrights' => '',
  'branding-dt_credits' => '1',
  'menu-parent_menu_clickable' => '1',
  'menu-first_font' => 'Tahoma',
  'menu-first_font_bold' => '1',
  'menu-first_font_italic' => '0',
  'menu-first_font_size' => '12',
  'menu-first_font_upper' => '1',
  'menu-first_font_color' => '#1a1a1a',
  'menu-first_font_color_active' => '#fafafa',
  'menu-first_hoover_line_color' => '#d6134a',
  'menu-first_hoover_color' => '#252525',
  'menu-first_hoover_opacity' => 100,
  'menu-second_font_color' => '#fafafa',
  'menu-second_font_color_active' => '#d6134a',
  'menu-second_bg_color' => '#1b1b1b',
  'menu-second_bg_opacity' => 100,
  'buttons-bg_color' => '#383838',
  'buttons-font_color' => '#ffffff',
  'buttons-font_shadow' => '#1a1a1a',
  'buttons-active_bg_color' => '#ca0e48',
  'buttons-active_font_color' => '#ffffff',
  'buttons-active_font_shadow' => '#85082f',
  'main-icons_style' => 'black',
  'main-icons_opacity' => 37,
  'main_bg-bg_color' => '#f0f0f0',
  'background-bg_image' => '/images/backgrounds/content/pattern-main/full/grunge_pattern-main.jpg',
  'main_bg-bg_repeat' => 'repeat',
  'main_bg-bg_vertical_pos' => 'top',
  'main_bg-bg_horizontal_pos' => 'center',
  'main_bg-bg_fixed' => '0',
  'main_bg-bg_mobile_hide' => '0',
  'main_bg-overlay_enable' => '0',
  'main_bg-overlay_image' => 'none',
  'divs_and_heads-content_wide_divider' => '/images/backgrounds/content/div-big/full/grunge_div-big.png',
  'divs_and_heads-content_wide_divider_repeatx' => '1',
  'divs_and_heads-content_narrow_divider' => '/images/backgrounds/content/div-small/full/grunge_div-small.png',
  'divs_and_heads-content_narrow_divider_repeatx' => '1',
  'widgetcodes-bg_color' => '#ffffff',
  'widgetcodes-bg_opacity' => 100,
  'header-icons_style' => 'black',
  'header-icons_opacity' => 58,
  'header-icons_bg_color' => '#ffffff',
  'header-icons_bg_opacity' => 17,
  'header_logo_menu-bg_color' => '#ffffff',
  'header_logo_menu-bg_image' => 'none',
  'header_logo_menu-bg_repeat' => 'repeat-x',
  'header_logo_menu-bg_vertical_pos' => 'top',
  'header_logo_menu-bg_horizontal_pos' => 'center',
  'header_homepage-bg_image' => '/images/backgrounds/header/art-header-main/full/grunge_art-header-main.jpg',
  'header_homepage-bg_repeat' => 'repeat-x',
  'header_homepage-bg_vertical_pos' => 'top',
  'header_homepage-bg_horizontal_pos' => 'center',
  'header_content-bg_image' => '/images/backgrounds/header/art-header-inner/full/grunge_art-header-inner.jpg',
  'header_content-bg_repeat' => 'repeat-x',
  'header_content-bg_vertical_pos' => 'top',
  'header_content-bg_horizontal_pos' => 'center',
  'top_line-bg_color' => '#252525',
  'top_line-bg_image' => 'none',
  'top_line-bg_repeat' => 'repeat',
  'top_line-bg_vertical_pos' => 'top',
  'top_line-bg_horizontal_pos' => 'center',
  'footer-bg_color' => '#7f7f7f',
  'footer-bg_opacity' => 13,
  'footer-bg_image' => 'none',
  'footer-bg_repeat' => 'repeat',
  'footer-bg_vertical_pos' => 'center',
  'footer-bg_horizontal_pos' => 'center',
  'divs_and_heads-footer_wide_divider' => 'none',
  'divs_and_heads-footer_wide_divider_hide_if_no_footer' => '0',
  'divs_and_heads-footer_wide_divider_repeatx' => '0',
  'widgetcodes_footer-bg_color' => '#ffffff',
  'widgetcodes_footer-bg_opacity' => 100,
  'bottom_line-bg_color' => '#252525',
  'bottom_line-bg_opacity' => 100,
  'bottom_line-bg_image' => 'none',
  'bottom_line-bg_repeat' => 'repeat',
  'bottom_line-bg_vertical_pos' => 'top',
  'bottom_line-bg_horizontal_pos' => 'center',
  'boxed_layout-enable' => '0',
  'boxed_layout-bg_color' => '#ffffff',
  'boxed_layout-bg_opacity' => 34,
  'boxed_layout-bg_image' => 'none',
  'boxed_layout-shadow_color' => '#000000',
  'boxed_layout-shadow_opacity' => 20,
  'accent-icons_style' => 'white',
  'accent-color' => '#d6134a',
  'fonts-font_family' => 'Arial_Bold',
  'fonts-font_size' => 12,
  'fonts_content-topline_color' => '#f5f5f5',
  'fonts_content-primary_color' => '#383838',
  'fonts_content-secondary_color' => '#858585',
  'fonts-links_text_color' => '#bd0b46',
  'fonts_footer-primary_color' => '#383838',
  'fonts_footer-secondary_color' => '#c1154e',
  'fonts_content-bottomline_color' => '#f5f5f5',
  'fonts-list' => 'Bitter',
  'fonts-headers_size_h1' => '27',
  'fonts-headers_size_h2' => '19',
  'fonts-headers_size_h3' => '16',
  'fonts-headers_size_h4' => '14',
  'fonts-headers_size_h5' => '12',
  'fonts-headers_size_h6' => '10',
  'fonts_content-headers_color' => '#0d0d0d',
  'fonts_footer-headers_bottom_color' => '#0d0d0d',
  'branding-favicon' => '',
  'header_logo_menu-height' => '100',
); ?>