<?php $presets["nature"] = array (
  'of-preset' => 'nature',
  'branding-header_logo' => 
  array (
    0 => '/images/backgrounds/branding/nature_logo-top.png?w=191&h=60',
    1 => 0,
  ),
  'branding-retina_header_logo' => 
  array (
    0 => '/images/backgrounds/branding/nature_logo-top-retina.png?w=382&h=120',
    1 => 0,
  ),
  'branding-header_mobile_logo' => 
  array (
    0 => '/images/backgrounds/branding/nature_logo-mob.png?w=144&h=150',
    1 => 0,
  ),
  'branding-retina_header_mobile_logo' => 
  array (
    0 => '/images/backgrounds/branding/nature_logo-mob-retina.png?w=288&h=300',
    1 => 0,
  ),
  'branding-footer_logo' => 
  array (
    0 => '/images/backgrounds/branding/nature_logo-bottom.png?w=151&h=50',
    1 => 0,
  ),
  'branding-retina_footer_logo' => 
  array (
    0 => '/images/backgrounds/branding/nature_logo-bottom-retina.png?w=302&h=100',
    1 => 0,
  ),
  'branding-copyrights' => '',
  'branding-dt_credits' => '1',
  'menu-parent_menu_clickable' => '1',
  'menu-first_font' => 'Tahoma',
  'menu-first_font_bold' => '1',
  'menu-first_font_italic' => '0',
  'menu-first_font_size' => '12',
  'menu-first_font_upper' => '1',
  'menu-first_font_color' => '#fafafa',
  'menu-first_font_color_active' => '#110b08',
  'menu-first_hoover_line_color' => '#8bb821',
  'menu-first_hoover_color' => '#ffffff',
  'menu-first_hoover_opacity' => 100,
  'menu-second_font_color' => '#110b08',
  'menu-second_font_color_active' => '#8bb821',
  'menu-second_bg_color' => '#ffffff',
  'menu-second_bg_opacity' => 100,
  'buttons-bg_color' => '#d74f0b',
  'buttons-font_color' => '#ffffff',
  'buttons-font_shadow' => '#a8400c',
  'buttons-active_bg_color' => '#87bd13',
  'buttons-active_font_color' => '#ffffff',
  'buttons-active_font_shadow' => '#638716',
  'main-icons_style' => 'white',
  'main-icons_opacity' => 78,
  'main_bg-bg_color' => '#1b1511',
  'background-bg_image' => '/images/backgrounds/content/pattern-main/full/nature_pattern-main.gif',
  'main_bg-bg_repeat' => 'full-screen',
  'main_bg-bg_vertical_pos' => 'center',
  'main_bg-bg_horizontal_pos' => 'center',
  'main_bg-bg_fixed' => '0',
  'main_bg-bg_mobile_hide' => '1',
  'main_bg-overlay_enable' => '0',
  'main_bg-overlay_image' => 'none',
  'divs_and_heads-content_wide_divider' => '/images/backgrounds/content/div-big/full/nature_div-big.png',
  'divs_and_heads-content_wide_divider_repeatx' => '1',
  'divs_and_heads-content_narrow_divider' => '/images/backgrounds/content/div-small/full/nature_div-small.png',
  'divs_and_heads-content_narrow_divider_repeatx' => '1',
  'widgetcodes-bg_color' => '#110b08',
  'widgetcodes-bg_opacity' => 100,
  'header-icons_style' => 'white',
  'header-icons_opacity' => 30,
  'header-icons_bg_color' => '#0b0705',
  'header-icons_bg_opacity' => 100,
  'header_logo_menu-bg_color' => '#110b08',
  'header_logo_menu-bg_image' => 'none',
  'header_logo_menu-bg_repeat' => 'repeat-x',
  'header_logo_menu-bg_vertical_pos' => 'bottom',
  'header_logo_menu-bg_horizontal_pos' => 'center',
  'header_homepage-bg_image' => 'none',
  'header_homepage-bg_repeat' => 'no-repeat',
  'header_homepage-bg_vertical_pos' => 'top',
  'header_homepage-bg_horizontal_pos' => 'center',
  'header_content-bg_image' => 'none',
  'header_content-bg_repeat' => 'no-repeat',
  'header_content-bg_vertical_pos' => 'top',
  'header_content-bg_horizontal_pos' => 'center',
  'top_line-bg_color' => '#1f1813',
  'top_line-bg_image' => '/images/backgrounds/header/line-top/full/nature_line-top.gif',
  'top_line-bg_repeat' => 'repeat',
  'top_line-bg_vertical_pos' => 'center',
  'top_line-bg_horizontal_pos' => 'center',
  'footer-bg_color' => '#110b08',
  'footer-bg_opacity' => 100,
  'footer-bg_image' => 'none',
  'footer-bg_repeat' => 'repeat',
  'footer-bg_vertical_pos' => 'center',
  'footer-bg_horizontal_pos' => 'center',
  'divs_and_heads-footer_wide_divider' => 'none',
  'divs_and_heads-footer_wide_divider_hide_if_no_footer' => '0',
  'divs_and_heads-footer_wide_divider_repeatx' => '1',
  'widgetcodes_footer-bg_color' => '#1e1713',
  'widgetcodes_footer-bg_opacity' => 100,
  'bottom_line-bg_color' => '#1f1813',
  'bottom_line-bg_opacity' => 100,
  'bottom_line-bg_image' => '/images/backgrounds/footer/line-bottom/full/nature_line-bottom.gif',
  'bottom_line-bg_repeat' => 'repeat',
  'bottom_line-bg_vertical_pos' => 'top',
  'bottom_line-bg_horizontal_pos' => 'center',
  'boxed_layout-enable' => '0',
  'boxed_layout-bg_color' => '#ffffff',
  'boxed_layout-bg_opacity' => 34,
  'boxed_layout-bg_image' => 'none',
  'boxed_layout-shadow_color' => '#000000',
  'boxed_layout-shadow_opacity' => 20,
  'accent-icons_style' => 'white',
  'accent-color' => '#8bb821',
  'fonts-font_family' => 'Arial_Bold',
  'fonts-font_size' => 12,
  'fonts_content-topline_color' => '#75706d',
  'fonts_content-primary_color' => '#807a77',
  'fonts_content-secondary_color' => '#f0f0f0',
  'fonts-links_text_color' => '#c8561d',
  'fonts_footer-primary_color' => '#dbdbdb',
  'fonts_footer-secondary_color' => '#c8561d',
  'fonts_content-bottomline_color' => '#75706d',
  'fonts-list' => 'Bitter',
  'fonts-headers_size_h1' => '27',
  'fonts-headers_size_h2' => '19',
  'fonts-headers_size_h3' => '16',
  'fonts-headers_size_h4' => '14',
  'fonts-headers_size_h5' => '12',
  'fonts-headers_size_h6' => '10',
  'fonts_content-headers_color' => '#f0f0f0',
  'fonts_footer-headers_bottom_color' => '#f0f0f0',
  'branding-favicon' => '',
  'header_logo_menu-height' => '100',
); ?>