<?php $presets["sweet"] = array (
  'of-preset' => 'sweet',
  'branding-header_logo' => 
  array (
    0 => '/images/backgrounds/branding/sweet_logo-top.png?w=195&h=60',
    1 => 0,
  ),
  'branding-retina_header_logo' => 
  array (
    0 => '/images/backgrounds/branding/sweet_logo-top-retina.png?w=390&h=120',
    1 => 0,
  ),
  'branding-header_mobile_logo' => 
  array (
    0 => '/images/backgrounds/branding/sweet_logo-mob.png?w=144&h=150',
    1 => 0,
  ),
  'branding-retina_header_mobile_logo' => 
  array (
    0 => '/images/backgrounds/branding/sweet_logo-mob-retina.png?w=288&h=300',
    1 => 0,
  ),
  'branding-footer_logo' => 
  array (
    0 => '/images/backgrounds/branding/sweet_logo-bottom.png?w=148&h=50',
    1 => 0,
  ),
  'branding-retina_footer_logo' => 
  array (
    0 => '/images/backgrounds/branding/sweet_logo-bottom-retina.png?w=296&h=100',
    1 => 0,
  ),
  'branding-copyrights' => '',
  'branding-dt_credits' => '1',
  'menu-parent_menu_clickable' => '1',
  'menu-first_font' => 'Tahoma',
  'menu-first_font_bold' => '1',
  'menu-first_font_italic' => '0',
  'menu-first_font_size' => '12',
  'menu-first_font_upper' => '1',
  'menu-first_font_color' => '#ffffff',
  'menu-first_font_color_active' => '#141414',
  'menu-first_hoover_line_color' => '#28bcd3',
  'menu-first_hoover_color' => '#ffffff',
  'menu-first_hoover_opacity' => 100,
  'menu-second_font_color' => '#141414',
  'menu-second_font_color_active' => '#0daac2',
  'menu-second_bg_color' => '#ffffff',
  'menu-second_bg_opacity' => 100,
  'buttons-bg_color' => '#12b7d2',
  'buttons-font_color' => '#ffffff',
  'buttons-font_shadow' => '#118799',
  'buttons-active_bg_color' => '#e3206a',
  'buttons-active_font_color' => '#ffffff',
  'buttons-active_font_shadow' => '#8f1443',
  'main-icons_style' => 'black',
  'main-icons_opacity' => 75,
  'main_bg-bg_color' => '#f4f4f4',
  'background-bg_image' => 'none',
  'main_bg-bg_repeat' => 'repeat',
  'main_bg-bg_vertical_pos' => 'top',
  'main_bg-bg_horizontal_pos' => 'center',
  'main_bg-bg_fixed' => '0',
  'main_bg-bg_mobile_hide' => '0',
  'main_bg-overlay_enable' => '0',
  'main_bg-overlay_image' => 'none',
  'divs_and_heads-content_wide_divider' => '/images/backgrounds/content/div-big/full/sweet_div-big.gif',
  'divs_and_heads-content_wide_divider_repeatx' => '1',
  'divs_and_heads-content_narrow_divider' => '/images/backgrounds/content/div-small/full/sweet_div-small.gif',
  'divs_and_heads-content_narrow_divider_repeatx' => '1',
  'widgetcodes-bg_color' => '#ffffff',
  'widgetcodes-bg_opacity' => 100,
  'header-icons_style' => 'black',
  'header-icons_opacity' => 70,
  'header-icons_bg_color' => '#e5e5e5',
  'header-icons_bg_opacity' => 100,
  'header_logo_menu-bg_color' => '#ffffff',
  'header_logo_menu-bg_image' => '/images/backgrounds/header/under-menu/full/sweet_under-menu.gif',
  'header_logo_menu-bg_repeat' => 'repeat-x',
  'header_logo_menu-bg_vertical_pos' => 'top',
  'header_logo_menu-bg_horizontal_pos' => 'center',
  'header_homepage-bg_image' => '/images/backgrounds/header/art-header-main/full/sweet_art-header-main.gif',
  'header_homepage-bg_repeat' => 'repeat-x',
  'header_homepage-bg_vertical_pos' => 'top',
  'header_homepage-bg_horizontal_pos' => 'center',
  'header_content-bg_image' => 'none',
  'header_content-bg_repeat' => 'repeat-x',
  'header_content-bg_vertical_pos' => 'top',
  'header_content-bg_horizontal_pos' => 'center',
  'top_line-bg_color' => '#ffffff',
  'top_line-bg_image' => 'none',
  'top_line-bg_repeat' => 'repeat',
  'top_line-bg_vertical_pos' => 'top',
  'top_line-bg_horizontal_pos' => 'center',
  'footer-bg_color' => '#ffffff',
  'footer-bg_opacity' => 100,
  'footer-bg_image' => 'none',
  'footer-bg_repeat' => 'repeat',
  'footer-bg_vertical_pos' => 'center',
  'footer-bg_horizontal_pos' => 'center',
  'divs_and_heads-footer_wide_divider' => '/images/backgrounds/footer/line-decor/full/sweet_line-decor.gif',
  'divs_and_heads-footer_wide_divider_hide_if_no_footer' => '0',
  'divs_and_heads-footer_wide_divider_repeatx' => '1',
  'widgetcodes_footer-bg_color' => '#f4f4f4',
  'widgetcodes_footer-bg_opacity' => 100,
  'bottom_line-bg_color' => '#c51354',
  'bottom_line-bg_opacity' => 100,
  'bottom_line-bg_image' => '/images/backgrounds/footer/line-bottom/full/sweet_line-bottom.gif',
  'bottom_line-bg_repeat' => 'repeat',
  'bottom_line-bg_vertical_pos' => 'top',
  'bottom_line-bg_horizontal_pos' => 'center',
  'boxed_layout-enable' => '0',
  'boxed_layout-bg_color' => '#ffffff',
  'boxed_layout-bg_opacity' => 34,
  'boxed_layout-bg_image' => 'none',
  'boxed_layout-shadow_color' => '#000000',
  'boxed_layout-shadow_opacity' => 20,
  'accent-icons_style' => 'white',
  'accent-color' => '#28bcd3',
  'fonts-font_family' => 'Arial_Bold',
  'fonts-font_size' => 12,
  'fonts_content-topline_color' => '#3b3b3b',
  'fonts_content-primary_color' => '#525252',
  'fonts_content-secondary_color' => '#e3206a',
  'fonts-links_text_color' => '#0ab0c9',
  'fonts_footer-primary_color' => '#525252',
  'fonts_footer-secondary_color' => '#0ab0c9',
  'fonts_content-bottomline_color' => '#ffffff',
  'fonts-list' => 'Bitter',
  'fonts-headers_size_h1' => '27',
  'fonts-headers_size_h2' => '19',
  'fonts-headers_size_h3' => '16',
  'fonts-headers_size_h4' => '14',
  'fonts-headers_size_h5' => '12',
  'fonts-headers_size_h6' => '10',
  'fonts_content-headers_color' => '#1e1e1d',
  'fonts_footer-headers_bottom_color' => '#1e1e1d',
  'branding-favicon' => '',
  'header_logo_menu-height' => '100',
); ?>