<?php $presets["wild"] = array (
  'of-preset' => 'wild',
  'branding-header_logo' => 
  array (
    0 => '/images/backgrounds/branding/wild_logo-top.png?w=192&h=60',
    1 => 0,
  ),
  'branding-retina_header_logo' => 
  array (
    0 => '/images/backgrounds/branding/wild_logo-top-retina.png?w=384&h=120',
    1 => 0,
  ),
  'branding-header_mobile_logo' => 
  array (
    0 => '/images/backgrounds/branding/wild_logo-mob.png?w=144&h=150',
    1 => 0,
  ),
  'branding-retina_header_mobile_logo' => 
  array (
    0 => '/images/backgrounds/branding/wild_logo-mob-retina.png?w=288&h=300',
    1 => 0,
  ),
  'branding-footer_logo' => 
  array (
    0 => '/images/backgrounds/branding/wild_logo-bottom.png?w=146&h=50',
    1 => 0,
  ),
  'branding-retina_footer_logo' => 
  array (
    0 => '/images/backgrounds/branding/wild_logo-bottom-retina.png?w=292&h=100',
    1 => 0,
  ),
  'branding-copyrights' => '',
  'branding-dt_credits' => '1',
  'menu-parent_menu_clickable' => '1',
  'menu-first_font' => 'Tahoma',
  'menu-first_font_bold' => '1',
  'menu-first_font_italic' => '0',
  'menu-first_font_size' => '12',
  'menu-first_font_upper' => '1',
  'menu-first_font_color' => '#ffffff',
  'menu-first_font_color_active' => '#808d8a',
  'menu-first_hoover_line_color' => '#898f8e',
  'menu-first_hoover_color' => '#000000',
  'menu-first_hoover_opacity' => 70,
  'menu-second_font_color' => '#0f0f0f',
  'menu-second_font_color_active' => '#ec3e08',
  'menu-second_bg_color' => '#ffffff',
  'menu-second_bg_opacity' => 100,
  'buttons-bg_color' => '#242424',
  'buttons-font_color' => '#ffffff',
  'buttons-font_shadow' => '#1f1f1f',
  'buttons-active_bg_color' => '#434747',
  'buttons-active_font_color' => '#ffffff',
  'buttons-active_font_shadow' => '#303333',
  'main-icons_style' => 'black',
  'main-icons_opacity' => 28,
  'main_bg-bg_color' => '#f6f5f3',
  'background-bg_image' => 'none',
  'main_bg-bg_repeat' => 'repeat',
  'main_bg-bg_vertical_pos' => 'top',
  'main_bg-bg_horizontal_pos' => 'center',
  'main_bg-bg_fixed' => '0',
  'main_bg-bg_mobile_hide' => '0',
  'main_bg-overlay_enable' => '0',
  'main_bg-overlay_image' => 'none',
  'divs_and_heads-content_wide_divider' => '/images/backgrounds/content/div-big/full/wild_div-big.gif',
  'divs_and_heads-content_wide_divider_repeatx' => '1',
  'divs_and_heads-content_narrow_divider' => '/images/backgrounds/content/div-small/full/wild_div-small.gif',
  'divs_and_heads-content_narrow_divider_repeatx' => '1',
  'widgetcodes-bg_color' => '#ffffff',
  'widgetcodes-bg_opacity' => 100,
  'header-icons_style' => 'black',
  'header-icons_opacity' => 83,
  'header-icons_bg_color' => '#ffffff',
  'header-icons_bg_opacity' => 19,
  'header_logo_menu-bg_color' => '#2d0001',
  'header_logo_menu-bg_image' => '/images/backgrounds/header/under-menu/full/wild_under-menu.gif',
  'header_logo_menu-bg_repeat' => 'repeat',
  'header_logo_menu-bg_vertical_pos' => 'top',
  'header_logo_menu-bg_horizontal_pos' => 'center',
  'header_homepage-bg_image' => '/images/backgrounds/header/art-header-main/full/wild_art-header-main.jpg',
  'header_homepage-bg_repeat' => 'repeat-x',
  'header_homepage-bg_vertical_pos' => 'top',
  'header_homepage-bg_horizontal_pos' => 'center',
  'header_content-bg_image' => '/images/backgrounds/header/art-header-inner/full/wild_art-header-inner-.gif',
  'header_content-bg_repeat' => 'repeat-x',
  'header_content-bg_vertical_pos' => 'top',
  'header_content-bg_horizontal_pos' => 'center',
  'top_line-bg_color' => '#000000',
  'top_line-bg_image' => 'none',
  'top_line-bg_repeat' => 'repeat',
  'top_line-bg_vertical_pos' => 'top',
  'top_line-bg_horizontal_pos' => 'center',
  'footer-bg_color' => '#000000',
  'footer-bg_opacity' => 100,
  'footer-bg_image' => 'none',
  'footer-bg_repeat' => 'repeat',
  'footer-bg_vertical_pos' => 'center',
  'footer-bg_horizontal_pos' => 'center',
  'divs_and_heads-footer_wide_divider' => 'none',
  'divs_and_heads-footer_wide_divider_hide_if_no_footer' => '0',
  'divs_and_heads-footer_wide_divider_repeatx' => '1',
  'widgetcodes_footer-bg_color' => '#2d2d2d',
  'widgetcodes_footer-bg_opacity' => 70,
  'bottom_line-bg_color' => '#2d2d2d',
  'bottom_line-bg_opacity' => 70,
  'bottom_line-bg_image' => 'none',
  'bottom_line-bg_repeat' => 'repeat',
  'bottom_line-bg_vertical_pos' => 'top',
  'bottom_line-bg_horizontal_pos' => 'center',
  'boxed_layout-enable' => '0',
  'boxed_layout-bg_color' => '#ffffff',
  'boxed_layout-bg_opacity' => 34,
  'boxed_layout-bg_image' => 'none',
  'boxed_layout-shadow_color' => '#000000',
  'boxed_layout-shadow_opacity' => 20,
  'accent-icons_style' => 'white',
  'accent-color' => '#8c8f8e',
  'fonts-font_family' => 'Arial_Bold',
  'fonts-font_size' => 12,
  'fonts_content-topline_color' => '#f2f2f2',
  'fonts_content-primary_color' => '#4d4a48',
  'fonts_content-secondary_color' => '#8c9190',
  'fonts-links_text_color' => '#e4410e',
  'fonts_footer-primary_color' => '#ceccca',
  'fonts_footer-secondary_color' => '#eb6303',
  'fonts_content-bottomline_color' => '#ceccca',
  'fonts-list' => 'Bitter',
  'fonts-headers_size_h1' => '27',
  'fonts-headers_size_h2' => '19',
  'fonts-headers_size_h3' => '16',
  'fonts-headers_size_h4' => '14',
  'fonts-headers_size_h5' => '12',
  'fonts-headers_size_h6' => '10',
  'fonts_content-headers_color' => '#292b2b',
  'fonts_footer-headers_bottom_color' => '#fafafa',
  'branding-favicon' => '',
  'header_logo_menu-height' => '100',
); ?>